### ISSUE TITLE
Survey with choices - Choices have wrong values after reordering

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3976] opened 2023-04-11 15:22 UTC
User issue: T12644 - Difficulty Editing Dropdown Choices in Multilingual Forms - Memory Issue
https://surveyjs.answerdesk.io/internal/ticket/details/T12644
***
To reproduce the issue, run this example: https://codesandbox.io/s/charming-star-5ht7q1?file=/src/survey_json.js

Drag the Albania choice below Bahamas: the Albania choice value changes to an incorrect value:
https://user-images.githubusercontent.com/22372972/231211034-d27fd46f-2227-4484-bf7a-1aea7402ba49.mp4

![image](https://user-images.githubusercontent.com/22372972/231210733-c2d9854d-221a-4bce-a63c-d672c9fbb62d.png)

**Comment by andrewtelnov** [comment] 2023-04-15 12:09
@dmitrykurmanov @JaneSjs The issue is fixed by PR in [the library issue](https://github.com/surveyjs/survey-library/pull/6030).
onCellCreated events/callback are not fired on moving a row and rows are not recreated. As result the issue is gone.

Thank you,
Andrew

**Closed** 2023-04-15 14:07 UTC
Labels: bug, user issue
