### ISSUE TITLE
Localization - Dynamic/Dropdown Matrix - The Edit Column dialog displays the default labels for Boolean columns

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3980] opened 2023-04-12 09:59 UTC
For a localized survey, the edit column dialog displays default labels instead of translated ones: [Example](https://plnkr.co/edit/GpYmUytmLxoFfUIW).

![image](https://user-images.githubusercontent.com/22372972/231424435-a20c1315-401a-4fa6-816b-30cb584ada82.png)

**Comment by tsv2013** [comment] 2023-04-27 15:34
All creator inner surveys except used in designer and preview tab are using current creator localization:
```TS
  public createSurvey(json: any = {}, reason: string = "designer"): SurveyModel {
    const survey = this.createSurveyCore(json, reason);
    if (reason === "designer" || reason === "modal-question-editor") {
      initializeDesignTimeSurveyModel(survey, this);
    }
    survey["needRenderIcons"] = false;
    if (reason != "designer" && reason != "test") {
      (<any>survey).locale = editorLocalization.currentLocale;
    }
    this.onSurveyInstanceCreated.fire(this, { survey: survey, reason: reason });
    return survey;
  }
```
Hence closing as "by design"

**Closed by tsv2013** 2023-04-27 15:34 UTC
Labels: question

**Comment by JaneSjs** [comment] 2023-04-28 13:38
To display the translated texts in the edit column dialog, it is necessary to set the `creator.locale` to the required locale:
```
creator.locale = 'fr';
```
The updated example is available at https://plnkr.co/edit/neiEtsNm23TD3rkG.
![image](https://user-images.githubusercontent.com/22372972/235162822-e7df4dae-7361-49d9-9bdc-542df19bb6ee.png)
