### ISSUE TITLE
Creator V2 for React change locale does not work 

### ISSUE THREAD

**Issue by jungsoo827** [surveyjs/survey-creator#2247] opened 2021-11-25 04:54 UTC
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Locale is changed, but designer does not refresh with new locale

### What is the expected behavior?

Designer refreshes with new locale.

### How would you reproduce the current behavior (if this is a bug)?

setting locale by survey.locale = 'ko'  does not change designer language

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
survey.locale = 'ko';
survey.render();

```

### Specify your

* browser: chrome
* editor version: 1.8.71 (using react)

**Comment by andrewtelnov** [comment] 2021-11-25 19:18
@jungsoo827 To be on one page. I have created [an example](https://plnkr.co/edit/5ueqtozgxQdl3wPV). I can see there is an issue with dropdown. It doesn't render correct string for "Choose...". We are going to fix it. Do you have other issues?

Thank you,
Andrew

**Comment by andrewtelnov** [comment] 2021-11-25 19:25
@jungsoo827 Never mind. I guess I found the cause of the problem. I will come back on this issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment] 2021-11-26 08:25
@jungsoo827 The issue is fixed by the commit above. I have added a new functional test.

Thank you,
Andrew

**Comment by jungsoo827** [comment] 2021-11-26 09:10
Thank you so much.^^

**Closed** 2021-11-26 14:43 UTC
Labels: bug, fixed
