### ISSUE TITLE
Scroll the page on adding new element from toolbox or selecting an element on the page

### ISSUE THREAD

**Issue by bhp2810** [surveyjs/survey-creator#601] opened 2019-09-20 11:27 UTC
### What is the current behavior?

Pick and drop anything from toolbox > Automatically scrolls up to the top of the page itself not even the builder.

### What is the expected behavior?

How to prevent to scroll when add element from Toolbox to Editor Area.

### How would you reproduce the current behavior (if this is a bug)?

Select and add element from toolbox.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment] 2019-09-20 18:00
@bhp2810 It tries to make the new question visible on the page by using scrollIntoView DOM function. We take a look.

Thank you,
Andrew

**Comment by bhp2810** [comment] 2019-09-23 10:22
is there any option to prevent this scroll? 

How can I give custom validation when fill form with required field?

One thing other I want to add custom button type element so it appear in toolbox area and when I click on it, it will add to form editor and also want to give some function call and so when click this button in question form it will open some popup etc.

**Comment by andrewtelnov** [comment] 2019-09-23 11:17
@bhp2810 I am working on issue right now and I hope to fix it today. 

Thank you,
Andrwe

**Comment by albertoVieiraNeto** [comment] 2019-09-23 14:15
i believe this is a Duplicate of #546,  do you guys already have a next release in mind?

**Comment by andrewtelnov** [comment] 2019-09-23 14:18
@albertoVieiraNeto We use to release every Tuesday. So, we are going to release new minor version tomorrow.

THank you,
Andrew

**Comment by bhp2810** [comment] 2019-09-24 13:13
Hello,

How can I get this update if I used this by including js files in header?

**Closed** 2019-09-25 11:00 UTC
Labels: bug, fixed

**Comment by andrewtelnov** [comment] 2019-09-25 11:02
@bhp2810 I guess you are using out cdn. Then the new version is 1.1.13, you have to change the version in the file path from what you have on "1.1.13" it in your header. 

Thank you,
Andrew
