### ISSUE TITLE
Theme Editor. Accent color changing + hovers.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#4577] opened 2023-09-09 07:44 UTC
https://github.com/surveyjs/survey-creator/assets/17025812/bc9d7bd3-4f9a-4fe8-a7fa-0f50ecf33901

**Comment by tsv2013** [comment] 2023-09-18 09:16
Closing since can't reproduce it right now.

**Closed by tsv2013** 2023-09-18 09:16 UTC
Labels: bug
