### ISSUE TITLE
error TS2304: Cannot find name 'SurveyEditor'.

### ISSUE THREAD

**Issue by ShanakaNCG** [surveyjs/survey-creator#501] opened 2019-04-12 07:18 UTC
In Angular : 7.3.8 I am getting a error 

ERROR in node_modules/surveyjs-editor/surveyeditor.d.ts(1950,25): error TS2304: Cannot find name 'SurveyEditor'.
src/app/survey.editor.component.ts(48,24): error TS2694: Namespace '"[my project path]/anguler-projects/surveyjs-angular-cli/node_modules/surveyjs-editor/surveyeditor"' has no exported member 'SurveyEditor'.
src/app/survey.editor.component.ts(59,36): error TS2339: Property 'SurveyEditor' does not exist on type 'typeof import("[my project path]/anguler-projects/surveyjs-angular-cli/node_modules/surveyjs-editor/surveyeditor")'.

I am using windows 10 OS to use survey js for my application

**Comment by tsv2013** [comment] 2019-04-12 08:29
Transferred fo the corresponding repo
Probably .d.ts generation bug

**Comment by Kleysonb** [comment] 2019-04-13 12:01
Same problem here...

**Comment by ShanakaNCG** [comment] 2019-04-15 02:49
> Same problem here...

Did you find the reason for this or a solution?

**Comment by tsv2013** [comment] 2019-04-15 09:04
I've reproduced the issue in our https://github.com/surveyjs/surveyjs_angular_cli repo. I'm working on it.

**Closed** 2019-04-15 10:47 UTC
Labels: bug, fixed

**Comment by tsv2013** [comment] 2019-04-15 10:49
I've fixed the issue. Fix will be available in the nearest update. Note that since v1.0.79 it is recommended to use SurveyCreator instead of SurveyEditor and survey-creator package instead of the surveyjs-editor
