### ISSUE TITLE
SurveyCreator compilation error

### ISSUE THREAD

**Issue by odaper** [surveyjs/survey-creator#1549] opened 2021-07-23 07:20 UTC
### Reporting a bug

I got a compilation error when serving my angular v11 (ivy disabled) application using the version 1.8.57 of surveyjs librairies (creator/knockout/core), if I switch to the previous version (1.8.56) my app compiles with no errors

The new versions should be compatible with angular apps 

Try to create an angular app and integrate the surveyjs librairies with angular example 

<img width="1280" alt="Screenshot 2021-07-23 at 08 14 41" src="https://user-images.githubusercontent.com/16231505/126749247-4ef6ac9a-8606-435c-96a7-53ce5bbf9859.png">

**Comment by dmitrykurmanov** [comment] 2021-07-23 07:41
duplicate of https://github.com/surveyjs/survey-creator/issues/1543

**Comment by dmitrykurmanov** [comment] 2021-07-23 09:04
@mheers @odaper I've tried several times locally but unfortunately can't manage to reproduce the problem.

Here is the [codesandbox example](https://codesandbox.io/s/surveyjs-angular-forked-rivo5) from our site with the latest versions of survey-library and survey-creator and it compiles without errors.

Could you please modify it to reproduce the problem? Or maybe the repo with the error will help us to understand what's going wrong.

Thanks,
Dmitry
SurveyJS Team

**Comment by odaper** [comment] 2021-07-23 09:53
Thanks @dmitrykurmanov for your help, my app uses angular v11 below the used versions:
`"@angular/animations": "^11.2.12",
    "@angular/cdk": "^11.2.12",
    "@angular/common": "^11.2.12",
    "@angular/compiler": "^11.2.12",
    "@angular/core": "^11.2.12",
    "@angular/forms": "^11.2.12",
    "@angular/localize": "^11.2.12",
    "@angular/platform-browser": "^11.2.12",
    "@angular/platform-browser-dynamic": "^11.2.12",
    "@angular/router": "^11.2.12",`

Below my tsconfig.json file:
`{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "module": "esnext",
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": false,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"],
    "baseUrl": "./",
    "paths": {
    }
  },
  "include": ["src/**/*"],
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "enableIvy": false
  }
}
`
Find attached a screenshot with a success compilation using 1.8.56 instead of 1.8.57 of 'survey-knockout' module and the others "survey-creator" "survey-angular"

<img width="1280" alt="surveyjs-1 8 56-works" src="https://user-images.githubusercontent.com/16231505/126765755-4f7ddb25-828c-4785-aabf-a1fe0cdcb134.png">

**Comment by dmitrykurmanov** [comment] 2021-07-23 18:44
unfortunately, it is hard to say what's wrong here without the reproducible sample. It looks ok in our [angular repo](https://github.com/surveyjs/surveyjs_angular_cli) and in our examples (I've posted CodeSandbox above).

It would be great if you modify that CodeSandbox to reproduce the issue or if you share some other reproducible sample with us. 

Maybe I can create a standard angular-cli 11 project. Than I  import survey-creator there and share it with you. Can it help?

Thanks,
Dmitry
SurveyJS Team

**Comment by dmitrykurmanov** [comment] 2021-07-31 14:12
I believe, it was fixed via the https://github.com/surveyjs/survey-creator/issues/1564

Please try to use v.1.8.58 or higher

Thanks,
Dmitry
SurveyJS Team

**Closed by dmitrykurmanov** 2021-07-31 14:12 UTC
Labels: question
