### ISSUE TITLE
V2: Review performance of importing translation data

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#1902] opened 2021-09-29 05:07 UTC
Translation import is slower in V2 comparing to V1

**Comment by andrewtelnov** [comment] 2021-10-01 14:45
@tsachinn07 @AbhishekKS Do you have a large survey with cvs import file? I could not find a good one. I want to test against the real data. If you have one, could you post it on our support form in a private ticket?

Thank you,
Andrew

**Comment by AbhishekKS** [comment] 2021-10-02 08:48
Hi @andrewtelnov,
We don't really have a large survey as of now nor have our customers created one so far. However, we did create some pre-defined surveys to be ready to use for our customers. But they are unfortunately not big either. However, I have tried modifying a pre-defined survey template we have by adding more questions (some questions could be repeated but that should be OK I guess to test our use case here). So here I have tested with 63 questions across 7 pages. When I tested this on V2, fortunately, I don't see any latency issue while working on the translation page or while importing translations. Performance seems to be on similar lines to V1. Everything seems to happen under 1 sec with 63 questions. You can verify it from your end using this template and see if there is any scope for further optimization at the code level.

One thing I noticed though, is nothing big, I notice the same behavior in V1 as well. The thing is say if a field translation in a different language happens to be the same exactly as in the default language, in JSON that individual language translation entry is removed. That means it picks the default key. This seems fine since the translation is a duplicate of the default field value. With this on the translation tab, labels in different languages which are exactly the same as the default label become blank. I feel this is fine but just wanted to check, maybe the end-user can still complain that even though it's duplicate to the default label we should continue to display it and not clear it on the translation tab. 
The example below for your reference:
Here Choice option with text **Neutral** has the same translation in Default English and Spanish language. So translation for the Spanish choice field is cleared because it's duplicate.

![image](https://user-images.githubusercontent.com/13827554/135709555-9684fc02-6b41-4676-b653-9335422ecc83.png)

**Survey JSON with 63 questions:**
[EngagementSurvey-JSON.txt](https://github.com/surveyjs/survey-creator/files/7271156/EngagementSurvey-JSON.txt)

Translation CSV file:
[ExportedTranslations.csv](https://github.com/surveyjs/survey-creator/files/7271157/ExportedTranslations.csv)


Thanks
Abhishek

**Comment by andrewtelnov** [comment] 2021-10-04 13:48
@AbhishekKS I have imported the performance and should be acceptable now.

Thank you,
Andrew

**Closed** 2021-10-05 07:44 UTC
Labels: fixed, performance issue, v2
